# Generated by Django 4.0.4 on 2022-06-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='uname',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='ustatus',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='usurname',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='status',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
